# This is a basic workflow to help you get started with Actions

name: Test provider

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every 12 hours
  schedule:
    - cron: "0 */12 * * *" # Runs at 00:00 and 12:00 UTC every day. 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  providers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: run tor
        run: |
          mkdir -p tor && sudo echo "SOCKSPort 0.0.0.0:9150" > ./tor/torrc
          docker run -d --network host --name=tor -v `pwd`/tor:/etc/tor connectical/tor
          sleep 10
          
       # Download the grpcurl
      - name: install grpcurl 1.8.0-socks5 fork
        run: |
          wget -c https://github.com/tiero/grpcurl/releases/download/v1.8.0-socks5/grpcurl_1.8.0-socks5_linux_x86_64.tar.gz -O - | tar -xz

      # Download the proto
      - name: Download the proto files
        run: |
          wget https://raw.githubusercontent.com/TDex-network/tdex-protobuf/beta/{types,swap,trade}.proto
          
      - name: Call all the Markets endpoint
        run: |
          for endpoint in $(cat registry.json | jq -c -r '.[].endpoint'); do
            endpoint_without_schema=$(echo ${endpoint} | grep -oP '(http|https)://\K\S+')
            onion='.onion'
            if [[ "$endpoint_without_schema" =~ .*"$onion".* ]]; then
              ./grpcurl -plaintext -proto trade.proto $endpoint_without_schema Trade.Markets
            else
              ./grpcurl -proto trade.proto $endpoint_without_schema Trade.Markets
            fi
          done


